config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    member do
      post '/create_comment' => 'posts#create_comment', as: 'create_comment_to'
      post '/like_post' =>  'posts#like_post', as: 'like_post_to'  
    end
  end
  
  
  devise_for :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments
    has_many :likes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :create_comment, :like_post]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @like = true
    if user_signed_in?
      @like = current_user.likes.find_by(post_id: @post.id).nil?
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def create_comment
    unless user_signed_in?
      respond_to do |format|
        format.js {render 'please_login.js.erb'}
      end
    end
    @c = @post.comments.create(
      body: params[:body]
      )
  end
  
  def like_post
    # puts "Like Post Sucess"
    unless user_signed_in?
      respond_to do |format|
        format.js {render 'please_login.js.erb'}
      end
    else
      if Like.where(user_id: current_user.id, post_id: @post.id).first.nil?
        @result = current_user.likes.create(post_id: @post.id)
        # puts "좋아요"
      else
        @result = current_user.likes.find_by(post_id: @post.id).destroy
        # puts "좋아요 취소"
      end
      # puts "test"
      # puts @result
      # puts @result.frozen?
      @result =  @result.frozen?
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%if user_signed_in? %>
  <%=link_to "로그아웃", destroy_user_session_path, method: :delete, data: {confirm: "로그아웃 하시겠습니까? "} %>
<%else%>
  <%=link_to "로그인", new_user_session_path%>
<%end%>
<%=link_to "홈으로", root_path %>





<div class="container">
  <!--posts에 있는 부분들이 적힌다.-->
  <%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/create_comment.js.erb
alert("댓글이 등록됨");
$('#body').val("");
$('#comment_table tbody').prepend(
`<tr>
    <td><%= @c.body %></td>
</tr>;
`
)

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/like_post.js.erb
alert("좋아요를 눌렀습니다.")
<!--if(<%#= @result %>) {-->
<!--    $('#like_button').text("Like").addClass("btn-info").removeClass("btn-danger");-->
<!--} else {-->
<!--    $('#like_button').text("Dislike").addClass("btn-danger").removeClass("btn-info");-->
<!--}-->
<!--console.log("done");-->
<!--$('#like_count').text(<#%=@post.likes.count%>)-->


<!--좋아요 취소
    test 
    true -->

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/please_login.js.erb
if(confirm("로그인이 필요합니다. \n 로그인 페이지로 이동하시겠습니까?"))
location.href = "<%=new_user_session_path%>"

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%=form_tag create_comment_to_post_path, id: "comment" do%>
  <%=text_field_tag :body %>
  <%=submit_tag "댓글쓰기"%>
<% end %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %> |
<% if @like %>
  <%= link_to "Like", like_post_to_post_path, id: "like_button", class: "btn btn-info" %>
<% else %>
  <%= link_to "Dislike", like_post_to_post_path, id: "like_button", class: "btn btn-danger" %>  
<% end %>

<span id='like_count'><%=@post.likes.count %></span>

<table class="table", id="comment_table">
  <thead>
    <tr>
      <td>댓글</td>
    </tr>
  </thead>
  
  <tbody>
    <% @post.comments.reverse.each do |p| %>
    <tr>
      <td><%=p.body %></td>
    </tr>
    <% end %>
  </tbody>
  
  <tfoot>
    <tr>
      <td>* 악성 댓글 주의 *</td>
    </tr>
  </tfoot>
</table>


<script>
  $(function() {
    
    $('#like_button').on('click', function(e) {
      e.preventDefault();
      console.log("Like Button Clicked");
      $.ajax({
        method: "POST",
        url: "<%=like_post_to_post_path %>"
      })
    })
    
    
    
    var form = $('#comment');
    console.log(form);
    form.on('submit', function(e) {
      console.log("haha");
      e.preventDefault();
      
      var contents = $('#body').val();
      console.log(contents);
      $.ajax({
        url: "<%=create_comment_to_post_path%>",
        method: "POST",
        data: {body: contents}
      })
    });
  })
  
</script>